version: '3.9'

services:
  postgres:
    container_name: 'obrio-test-task-db'
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - obrio-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  obrio-db-volume:
